### ISSUE TITLE
Database errors while using dashdb on Bluemix

### ISSUE THREAD

**Issue by rvennam** [blueperf/acmeair-monolithic-java#2]
Now that sqldb is no longer available, and the recommended SQL database is dashdb, I tried it on Bluemix and see the following errors.

```
2016-09-01T15:35:36.46-0400 [App/0]      ERR Runtime Exceptions: 
2016-09-01T15:35:36.46-0400 [App/0]      ERR ---------------------------------------------------------
2016-09-01T15:35:36.76-0400 [App/0]      ERR [err]  at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createDeployFailedPersistenceException(EntityManagerSetupImpl.java:891)
2016-09-01T15:35:36.77-0400 [App/0]      ERR [err]  at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:831)
2016-09-01T15:35:36.77-0400 [App/0]      ERR [err]  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:207)
2016-09-01T15:35:36.81-0400 [App/0]      ERR [err]  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:307)
2016-09-01T15:35:36.81-0400 [App/0]      ERR [err]  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
2016-09-01T15:35:36.81-0400 [App/0]      ERR [err]  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:318)
2016-09-01T15:35:36.82-0400 [App/0]      ERR [err]  at com.ibm.ws.jpa.container.v21.internal.JPA21Runtime.createEntityManagerInstance(JPA21Runtime.java:104)
2016-09-01T15:35:36.82-0400 [App/0]      ERR [err]  at [internal classes]
2016-09-01T15:35:36.82-0400 [App/0]      ERR [err]  at com.acmeair.jpa.service.CustomerServiceImpl.getCustomerByUsername(CustomerServiceImpl.java:94)
2016-09-01T15:35:36.83-0400 [App/0]      ERR [err]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-09-01T15:35:36.87-0400 [App/0]      ERR [err]  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-09-01T15:35:36.88-0400 [App/0]      ERR [err]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
```

Before I did too much into it, wanted to see if this was a known issue with a solution.

**Comment by mossuchida** [comment]
Hi, Ram, Welcome back from your trip! I saw your photos!  anyway, we haven't tried dashdb, I am assuming there are some issues using different db (We are mostly using Mongo DB). btw, JPA degrades performance (if not coded carefully), we usually don't use it.

**Comment by rvennam** [comment]
@mossuchida, Thanks...It was a great trip and coming back was surely a jolt! 

I just realized I accidentally opened up this issue in the wrong repo! I meant to open this for the acmeair monolith app: https://github.com/WASdev/sample.acmeair.
